'use client';

import React from 'react';
import {
  BookOpen,
  Brain,
  Bot,
  Flame,
  Sparkles,
  Wand2,
  HelpCircle,
  Home,
  Calendar,
  BarChart2,
  TrendingUp,
  TrendingDown,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Search,
  Bookmark,
  Volume2,
  Headphones,
  Star,
  StarHalf,
  Timer,
  CheckCircle2,
  CheckCircle,
  Circle,
  X,
  RotateCw,
  RotateCcw,
  Play,
  Pause,
  FastForward,
  History,
  Shield,
  Settings,
  GraduationCap,
  FlaskConical,
  Activity,
  User,
  Users,
  AlertTriangle,
  Info,
  Download,
  Upload,
  Send,
  Share2,
  Edit3,
  Copy,
  Trash2,
  Rocket,
  BatteryMedium,
  Wifi,
  Maximize2,
  Target,
  Gauge,
  Lightbulb,
  Lock,
  Unlock,
  ThumbsUp,
  ThumbsDown,
  MoreVertical,
  Filter,
  Layers,
  GitBranch,
  Database,
  Table,
  FileText,
  FileDown,
  Printer,
  ArrowLeftRight,
  ArrowUpDown,
  Shuffle,
  Network,
  Pointer,
  MessageSquare,
  Flag,
  Code,
  Link as LinkIcon,
  Tag,
  Mic,
  Radio,
  Cpu,
  Camera,
  PieChart,
  ListOrdered,
  Quote,
  ZoomIn,
  Glasses,
  Folder,
  Image as ImageIcon,
  Crop,
  PenTool,
  Leaf,
  Zap,
  Smile,
  Meh,
  Check,
  Plus,
  Minus,
  ArrowRight,
  ArrowLeft,
  Scale,
  Clock,
  LucideIcon,
} from 'lucide-react';

interface StitchIconProps {
  name: string;
  className?: string;
  size?: number | string;
  fill?: boolean;
  style?: React.CSSProperties;
}

const ICON_MAP: Record<string, LucideIcon> = {
  // Navigation & Core
  home: Home,
  event_note: Calendar,
  event: Calendar,
  calendar_today: Calendar,
  calendar_clock: Calendar,
  calendar_month: Calendar,
  auto_schedule: Calendar,
  schedule: Clock,
  update: Clock,
  quiz: HelpCircle,
  insights: BarChart2,
  analytics: BarChart2,
  bar_chart: BarChart2,
  query_stats: BarChart2,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  smart_toy: Bot,
  assistant: Bot,
  psychology: Brain,
  psychology_alt: Brain,
  neurology: Brain,
  menu_book: BookOpen,
  auto_stories: BookOpen,
  book_4: BookOpen,
  library_books: BookOpen,
  local_fire_department: Flame,
  auto_awesome: Sparkles,
  auto_fix_high: Wand2,
  magic_button: Wand2,
  
  // Arrows & Chevron
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  keyboard_arrow_down: ChevronDown,
  arrow_back: ArrowLeft,
  arrow_back_ios: ChevronLeft,
  arrow_back_ios_new: ChevronLeft,
  arrow_forward: ArrowRight,
  arrow_forward_ios: ChevronRight,
  subdirectory_arrow_right: ArrowRight,
  arrow_left: ArrowLeft,
  arrow_right: ArrowRight,
  swap_horiz: ArrowLeftRight,
  swap_vert: ArrowUpDown,
  compare_arrows: ArrowLeftRight,
  compare: ArrowLeftRight,
  alt_route: GitBranch,
  shuffle: Shuffle,
  repeat_one: RotateCcw,
  
  // Search & Library
  search: Search,
  image_search: Search,
  zoom_in: ZoomIn,
  bookmark: Bookmark,
  bookmark_border: Bookmark,
  bookmark_add: Bookmark,
  bookmark_added: Bookmark,
  bookmark_heart: Bookmark,
  folder_special: Folder,
  history_edu: History,
  history: History,
  
  // Audio & Voice
  volume_up: Volume2,
  graphic_eq: Volume2,
  music_note: Volume2,
  audio_file: Volume2,
  voice_selection: Volume2,
  record_voice_over: Volume2,
  headphones: Headphones,
  mic: Mic,
  star: Star,
  grade: Star,
  star_half: StarHalf,
  timer: Timer,
  alarm: Timer,
  hourglass_top: Timer,
  timelapse: Timer,
  lock_clock: Timer,
  
  // Status & Validation
  check: Check,
  done: Check,
  done_all: Check,
  check_circle: CheckCircle2,
  task_alt: CheckCircle2,
  fact_check: CheckCircle2,
  rule: CheckCircle2,
  verified: CheckCircle2,
  verified_user: CheckCircle2,
  close: X,
  cancel: X,
  clear_all: X,
  add: Plus,
  add_circle: Plus,
  remove: Minus,
  radio_button_checked: CheckCircle,
  radio_button_unchecked: Circle,
  flag: Flag,
  flaky: AlertTriangle,
  
  // Media & Controls
  play_arrow: Play,
  play_circle: Play,
  pause: Pause,
  pause_circle: Pause,
  forward_10: FastForward,
  replay_10: RotateCcw,
  replay: RotateCcw,
  refresh: RotateCw,
  sync: RotateCw,
  sync_alt: RotateCw,
  cloud_sync: RotateCw,
  autorenew: RotateCw,
  restart_alt: RotateCw,
  touch_app: Pointer,
  flip: ArrowLeftRight,
  
  // Security & User
  admin_panel_settings: Shield,
  security: Shield,
  shield: Shield,
  shield_person: Shield,
  shield_with_heart: Shield,
  settings: Settings,
  tune: Settings,
  person: User,
  group: Users,
  groups: Users,
  how_to_reg: User,
  school: GraduationCap,
  military_tech: GraduationCap,
  
  // Science & Medical
  science: FlaskConical,
  biotech: FlaskConical,
  microbiology: FlaskConical,
  medical_services: Activity,
  vital_signs: Activity,
  balance: Scale,
  
  // Alerts & Notifications
  warning: AlertTriangle,
  priority_high: AlertTriangle,
  notification_important: AlertTriangle,
  notifications_active: AlertTriangle,
  crisis_alert: AlertTriangle,
  report: AlertTriangle,
  info: Info,
  help_outline: HelpCircle,
  
  // Data, Documents & Utilities
  download: Download,
  upload_file: Upload,
  post_add: Plus,
  note_add: Plus,
  assignment_add: Plus,
  send: Send,
  send_to_mobile: Send,
  share: Share2,
  edit_note: Edit3,
  content_copy: Copy,
  delete_sweep: Trash2,
  delete: Trash2,
  rocket_launch: Rocket,
  battery_full: BatteryMedium,
  wifi: Wifi,
  fullscreen: Maximize2,
  open_in_full: Maximize2,
  open_in_new: Maximize2,
  target: Target,
  track_changes: Target,
  speed: Gauge,
  lightbulb: Lightbulb,
  lock: Lock,
  lock_open: Unlock,
  thumb_up: ThumbsUp,
  thumb_down: ThumbsDown,
  more_vert: MoreVertical,
  filter_alt: Filter,
  filter_list: Filter,
  layers: Layers,
  grid_view: Layers,
  database: Database,
  dns: Database,
  dataset: Database,
  table_chart: Table,
  table_rows: Table,
  checklist: FileText,
  assignment: FileText,
  description: FileText,
  document_scanner: FileText,
  assignment_late: FileText,
  filetext: FileText,
  picture_as_pdf: FileText,
  pdf: FileDown,
  print: Printer,
  photo_camera: ImageIcon,
  camera: Camera,
  image: ImageIcon,
  crop: Crop,
  draw: PenTool,
  brush: PenTool,
  eco: Leaf,
  spa: Leaf,
  bolt: Zap,
  chat: MessageSquare,
  code: Code,
  link: LinkIcon,
  label: Tag,
  sell: Tag,
  radar: Radio,
  sensors: Radio,
  memory: Cpu,
  pending_actions: Clock,
  progress_activity: RotateCw,
  donut_large: PieChart,
  format_list_numbered: ListOrdered,
  format_quote: Quote,
  eyeglasses_2: Glasses,
  device_hub: Network,
  hub: Network,
  account_tree: Network,
  schema: Network,
  blur_on: Sparkles,
  functions: Code,
  sentiment_satisfied: Smile,
  sentiment_very_satisfied: Smile,
  sentiment_neutral: Meh,
};

export function StitchIcon({
  name,
  className = '',
  size = 20,
  fill = false,
  style,
}: StitchIconProps) {
  // Normalize icon name
  const cleanName = (name || '').trim().toLowerCase();
  const IconComponent = ICON_MAP[cleanName] || Sparkles;

  const numericSize =
    typeof size === 'number'
      ? size
      : typeof size === 'string' && size.endsWith('px')
      ? parseInt(size, 10)
      : 20;

  return (
    <IconComponent
      size={numericSize}
      className={`inline-block shrink-0 transition-colors ${className}`}
      style={{
        ...style,
        ...(fill ? { fill: 'currentColor' } : {}),
      }}
      aria-hidden="true"
    />
  );
}

export default StitchIcon;
