# Representative 50-Question Dataset for Phase 3 Quality Gate
# Spans Biology (18), Physics (16), Chemistry (16)
# Across: Single Correct, Assertion-Reason, Statement-based, Matching, Numerical, Diagram-based, Passage

GATE_QUESTIONS = [
    # ==================== BIOLOGY: REAL PYQ (8 Questions) ====================
    {
        "id": "Q_PYQ_NEET_2018_BIO_146",
        "stem": "The contraceptive 'SAHELI'",
        "options": [
            {"label": "A", "text": "is an IUD"},
            {"label": "B", "text": "increases the concentration of estrogen and prevents ovulation in females"},
            {"label": "C", "text": "blocks estrogen receptors in the uterus, preventing eggs from getting implanted"},
            {"label": "D", "text": "is a post-coital contraceptive"}
        ],
        "correctAnswer": "C",
        "explanation": "Saheli is a non-steroidal, once-a-week pill containing centchroman. It selectively blocks estrogen receptors in the endometrium, preventing implantation.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "MEDIUM",
        "subject": "BIOLOGY",
        "chapterBookCode": "lebo103",
        "chapterTitle": "Reproductive Health",
        "sourceType": "PYQ",
        "examName": "NEET",
        "examYear": 2018,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "146",
        "sourceDocument": "NEET (UG) 2018 Code AA",
        "sourcePage": 31
    },
    {
        "id": "Q_PYQ_NEET_2018_BIO_147",
        "stem": "Ciliates differ from all other protozoans in",
        "options": [
            {"label": "A", "text": "using pseudopodia for capturing prey"},
            {"label": "B", "text": "having a contractile vacuole for removing excess water"},
            {"label": "C", "text": "using flagella for locomotion"},
            {"label": "D", "text": "having two types of nuclei"}
        ],
        "correctAnswer": "D",
        "explanation": "Ciliates exhibit nuclear dimorphism, possessing a macronucleus (vegetative function) and a micronucleus (reproductive function).",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "HARD",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo102",
        "chapterTitle": "Biological Classification",
        "sourceType": "PYQ",
        "examName": "NEET",
        "examYear": 2018,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "147",
        "sourceDocument": "NEET (UG) 2018 Code AA",
        "sourcePage": 31
    },
    {
        "id": "Q_PYQ_NEET_2015_BIO_001",
        "stem": "In his classic experiments on pea plants, Mendel did not use:",
        "options": [
            {"label": "A", "text": "Pod length"},
            {"label": "B", "text": "Seed shape"},
            {"label": "C", "text": "Flower position"},
            {"label": "D", "text": "Seed colour"}
        ],
        "correctAnswer": "A",
        "explanation": "Mendel studied 7 pairs of contrasting traits: stem height, flower colour, flower position, pod shape, pod colour, seed shape, and seed colour. He did not study pod length.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "EASY",
        "subject": "BIOLOGY",
        "chapterBookCode": "lebo104",
        "chapterTitle": "Principles of Inheritance and Variation",
        "sourceType": "PYQ",
        "examName": "NEET",
        "examYear": 2015,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "1",
        "sourceDocument": "NEET Re-AIPMT 2015",
        "sourcePage": 1
    },
    {
        "id": "Q_PYQ_NEET_2015_BIO_091",
        "stem": "Gause's principle of competitive exclusion states that:",
        "options": [
            {"label": "A", "text": "More abundant species will exclude the less abundant species through competition"},
            {"label": "B", "text": "Competition for the same resources excludes species having different food preferences"},
            {"label": "C", "text": "No two species can occupy the same niche indefinitely for the same limiting resources"},
            {"label": "D", "text": "Larger organisms exclude smaller organisms through competition"}
        ],
        "correctAnswer": "C",
        "explanation": "Gause's Competitive Exclusion Principle states that two closely related species competing for the same limiting resources cannot coexist indefinitely, and the competitively inferior one will be eliminated.",
        "questionType": "STATEMENT_BASED",
        "difficulty": "MEDIUM",
        "subject": "BIOLOGY",
        "chapterBookCode": "lebo111",
        "chapterTitle": "Organisms and Populations",
        "sourceType": "PYQ",
        "examName": "NEET",
        "examYear": 2015,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "91",
        "sourceDocument": "NEET Re-AIPMT 2015",
        "sourcePage": 8
    },
    {
        "id": "Q_PYQ_AIIMS_2006_BIO_112",
        "stem": "In cyclic photophosphorylation, the primary electron acceptor is an iron-sulfur protein complex that receives electrons directly from:",
        "options": [
            {"label": "A", "text": "Photosystem II (P680)"},
            {"label": "B", "text": "Photosystem I (P700)"},
            {"label": "C", "text": "Plastoquinone"},
            {"label": "D", "text": "Cytochrome b6-f"}
        ],
        "correctAnswer": "B",
        "explanation": "In cyclic photophosphorylation, only PS I (P700) is functional. The excited electron is expelled from P700 and picked up by primary acceptor (Fe-S complex) before cycling back via cytochrome complex.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "MEDIUM",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo111",
        "chapterTitle": "Photosynthesis in Higher Plants",
        "sourceType": "PYQ",
        "examName": "AIIMS",
        "examYear": 2006,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "112",
        "sourceDocument": "AIIMS 2006 Solved Paper",
        "sourcePage": 18
    },
    {
        "id": "Q_PYQ_AIIMS_2007_BIO_085",
        "stem": "Assertion: Human females show cessation of menstrual cycles at around 50 years of age.\nReason: Ovary ceases to respond to gonadotropins due to exhaustion of primary follicles at menopause.",
        "options": [
            {"label": "A", "text": "Both assertion and reason are true and reason is the correct explanation of assertion"},
            {"label": "B", "text": "Both assertion and reason are true but reason is not the correct explanation of assertion"},
            {"label": "C", "text": "Assertion is true but reason is false"},
            {"label": "D", "text": "Both assertion and reason are false"}
        ],
        "correctAnswer": "A",
        "explanation": "Menopause occurs around age 50 because the ovary's reservoir of primordial follicles is depleted, so high levels of FSH and LH can no longer stimulate follicular growth or estrogen secretion.",
        "questionType": "ASSERTION_REASON",
        "difficulty": "HARD",
        "subject": "BIOLOGY",
        "chapterBookCode": "lebo102",
        "chapterTitle": "Human Reproduction",
        "sourceType": "PYQ",
        "examName": "AIIMS",
        "examYear": 2007,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "85",
        "sourceDocument": "AIIMS 2007 Solved Paper",
        "sourcePage": 22
    },
    {
        "id": "Q_PYQ_AIIMS_2008_BIO_092",
        "stem": "Assertion: Darwin's finches of Galapagos islands are an excellent example of adaptive radiation.\nReason: From the original seed-eating ancestral birds, different forms arose with beaks suited for feeding on insects, cactus, and fruit.",
        "options": [
            {"label": "A", "text": "Both assertion and reason are true and reason is the correct explanation of assertion"},
            {"label": "B", "text": "Both assertion and reason are true but reason is not the correct explanation of assertion"},
            {"label": "C", "text": "Assertion is true but reason is false"},
            {"label": "D", "text": "Both assertion and reason are false"}
        ],
        "correctAnswer": "A",
        "explanation": "Adaptive radiation is the process of evolution of different species in a given geographical area starting from a point and radiating to other habitats, as seen in Galapagos finches.",
        "questionType": "ASSERTION_REASON",
        "difficulty": "MEDIUM",
        "subject": "BIOLOGY",
        "chapterBookCode": "lebo106",
        "chapterTitle": "Evolution",
        "sourceType": "PYQ",
        "examName": "AIIMS",
        "examYear": 2008,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "92",
        "sourceDocument": "AIIMS 2008 Solved Paper",
        "sourcePage": 24
    },
    {
        "id": "Q_PYQ_AIPMT_2014_BIO_125",
        "stem": "During DNA replication, the discontinuous synthesis of DNA on the lagging strand produces Okazaki fragments that are joined by the enzyme:",
        "options": [
            {"label": "A", "text": "DNA ligase"},
            {"label": "B", "text": "DNA polymerase III"},
            {"label": "C", "text": "Helicase"},
            {"label": "D", "text": "Topoisomerase"}
        ],
        "correctAnswer": "A",
        "explanation": "DNA ligase catalyzes the formation of phosphodiester bonds to join the discontinuous Okazaki fragments on the lagging strand.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "EASY",
        "subject": "BIOLOGY",
        "chapterBookCode": "lebo105",
        "chapterTitle": "Molecular Basis of Inheritance",
        "sourceType": "PYQ",
        "examName": "AIPMT",
        "examYear": 2014,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "125",
        "sourceDocument": "AIPMT 2014 Solved Paper",
        "sourcePage": 42
    },

    # ==================== PHYSICS: REAL PYQ (11 Questions) ====================
    {
        "id": "Q_PYQ_NEET_2018_PHY_001",
        "stem": "The volume (V) of a monatomic gas varies with its temperature (T), as shown in the graph. The ratio of work done by the gas, to the heat absorbed by it, when it undergoes a change from state A to state B, is:",
        "options": [
            {"label": "A", "text": "1/3"},
            {"label": "B", "text": "2/3"},
            {"label": "C", "text": "2/5"},
            {"label": "D", "text": "2/7"}
        ],
        "correctAnswer": "C",
        "explanation": "For an isobaric expansion of a monatomic gas, dW = nR dT, and dQ = nCp dT = n(5/2 R) dT. Therefore, ratio dW/dQ = nR dT / (5/2 nR dT) = 2/5.",
        "questionType": "NUMERICAL",
        "difficulty": "MEDIUM",
        "subject": "PHYSICS",
        "chapterBookCode": "keph204",
        "chapterTitle": "Thermodynamics",
        "sourceType": "PYQ",
        "examName": "NEET",
        "examYear": 2018,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "1",
        "sourceDocument": "NEET (UG) 2018 Code AA",
        "sourcePage": 2
    },
    {
        "id": "Q_PYQ_NEET_2018_PHY_005",
        "stem": "A carbon resistor of (47 ± 4.7) kΩ is to be marked with rings of different colours for its identification. The colour code sequence will be:",
        "options": [
            {"label": "A", "text": "Yellow – Green – Violet – Gold"},
            {"label": "B", "text": "Yellow – Violet – Orange – Silver"},
            {"label": "C", "text": "Violet – Yellow – Orange – Silver"},
            {"label": "D", "text": "Green – Orange – Violet – Gold"}
        ],
        "correctAnswer": "B",
        "explanation": "47 kΩ ± 10% = 47 × 10³ Ω ± 10%. Band 1: 4 = Yellow; Band 2: 7 = Violet; Band 3: Multiplier 10³ = Orange; Band 4: Tolerance ±10% = Silver.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "EASY",
        "subject": "PHYSICS",
        "chapterBookCode": "leph103",
        "chapterTitle": "Current Electricity",
        "sourceType": "PYQ",
        "examName": "NEET",
        "examYear": 2018,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "5",
        "sourceDocument": "NEET (UG) 2018 Code AA",
        "sourcePage": 3
    },
    {
        "id": "Q_PYQ_NEET_2018_PHY_006",
        "stem": "A set of 'n' equal resistors, of value 'R' each, are connected in series to a battery of emf 'E' and internal resistance 'R'. The current drawn is I. Now, the 'n' resistors are connected in parallel to the same battery. Then the current drawn from battery becomes 10 I. The value of 'n' is:",
        "options": [
            {"label": "A", "text": "20"},
            {"label": "B", "text": "11"},
            {"label": "C", "text": "10"},
            {"label": "D", "text": "9"}
        ],
        "correctAnswer": "C",
        "explanation": "In series: I = E / (nR + R) = E / [R(n + 1)]. In parallel: Req = R/n. Total current I' = E / (R/n + R) = nE / [R(n + 1)]. I' / I = n = 10.",
        "questionType": "NUMERICAL",
        "difficulty": "HARD",
        "subject": "PHYSICS",
        "chapterBookCode": "leph103",
        "chapterTitle": "Current Electricity",
        "sourceType": "PYQ",
        "examName": "NEET",
        "examYear": 2018,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "6",
        "sourceDocument": "NEET (UG) 2018 Code AA",
        "sourcePage": 3
    },
    {
        "id": "Q_PYQ_AIPMT_2014_PHY_001",
        "stem": "If force (F), velocity (V) and time (T) are taken as fundamental units, then the dimensions of mass are:",
        "options": [
            {"label": "A", "text": "[F V T⁻¹]"},
            {"label": "B", "text": "[F V T⁻²]"},
            {"label": "C", "text": "[F V⁻¹ T⁻¹]"},
            {"label": "D", "text": "[F V⁻¹ T]"}
        ],
        "correctAnswer": "D",
        "explanation": "Let M = F^a V^b T^c. [M¹L⁰T⁰] = [M L T⁻²]^a [L T⁻¹]^b [T]^c. Equating powers gives a = 1, b = -1, c = 1. Thus [M] = [F V⁻¹ T].",
        "questionType": "NUMERICAL",
        "difficulty": "MEDIUM",
        "subject": "PHYSICS",
        "chapterBookCode": "keph101",
        "chapterTitle": "Units and Measurements",
        "sourceType": "PYQ",
        "examName": "AIPMT",
        "examYear": 2014,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "1",
        "sourceDocument": "AIPMT 2014 Solved Paper",
        "sourcePage": 1
    },
    {
        "id": "Q_PYQ_AIPMT_2014_PHY_003",
        "stem": "A particle is moving such that its position coordinates (x, y) are (2m, 3m) at time t = 0, (6m, 7m) at time t = 2 s and (13m, 14m) at time t = 5 s. Average velocity vector V_av from t = 0 to t = 5 s is:",
        "options": [
            {"label": "A", "text": "1/5 (13 î + 14 ĵ)"},
            {"label": "B", "text": "7/3 (î + ĵ)"},
            {"label": "C", "text": "2 (î + ĵ)"},
            {"label": "D", "text": "11/5 (î + ĵ)"}
        ],
        "correctAnswer": "D",
        "explanation": "V_av = Δr / Δt = [(13 - 2)î + (14 - 3)ĵ] / (5 - 0) = (11î + 11ĵ) / 5 = 11/5 (î + ĵ).",
        "questionType": "NUMERICAL",
        "difficulty": "EASY",
        "subject": "PHYSICS",
        "chapterBookCode": "keph103",
        "chapterTitle": "Motion in a Plane",
        "sourceType": "PYQ",
        "examName": "AIPMT",
        "examYear": 2014,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "3",
        "sourceDocument": "AIPMT 2014 Solved Paper",
        "sourcePage": 2
    },
    {
        "id": "Q_PYQ_AIPMT_2014_PHY_005",
        "stem": "The force 'F' acting on a particle of mass 'm' is indicated by the force-time graph shown below. The change in momentum of the particle over the time interval from zero to 8 s is:",
        "options": [
            {"label": "A", "text": "24 Ns"},
            {"label": "B", "text": "20 Ns"},
            {"label": "C", "text": "12 Ns"},
            {"label": "D", "text": "6 Ns"}
        ],
        "correctAnswer": "C",
        "explanation": "Change in momentum Δp = Area under F-t graph. Area = (1/2 × 2 × 6) - (2 × 3) + (4 × 3) = 6 - 6 + 12 = 12 Ns.",
        "questionType": "DIAGRAM_BASED",
        "difficulty": "MEDIUM",
        "subject": "PHYSICS",
        "chapterBookCode": "keph104",
        "chapterTitle": "Laws of Motion",
        "sourceType": "PYQ",
        "examName": "AIPMT",
        "examYear": 2014,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "5",
        "sourceDocument": "AIPMT 2014 Solved Paper",
        "sourcePage": 3,
        "diagramPath": "/extracted_figures/aipmt_2014_q5_ft_graph.png"
    },
    {
        "id": "Q_PYQ_AIIMS_2006_PHY_002",
        "stem": "Two spheres of same size, one of mass 2 kg and another of mass 4 kg are dropped simultaneously from the top of Qutab Minar (height = 72m). When they are 1 m above the ground the two spheres have the same:",
        "options": [
            {"label": "A", "text": "momentum"},
            {"label": "B", "text": "kinetic energy"},
            {"label": "C", "text": "potential energy"},
            {"label": "D", "text": "acceleration"}
        ],
        "correctAnswer": "D",
        "explanation": "Acceleration due to gravity (g) is independent of the mass of the falling object. Both accelerate at g = 9.8 m/s².",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "EASY",
        "subject": "PHYSICS",
        "chapterBookCode": "keph104",
        "chapterTitle": "Laws of Motion",
        "sourceType": "PYQ",
        "examName": "AIIMS",
        "examYear": 2006,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "2",
        "sourceDocument": "AIIMS 2006 Solved Paper",
        "sourcePage": 1
    },
    {
        "id": "Q_PYQ_AIIMS_2006_PHY_015",
        "stem": "For inelastic collision between two spherical rigid bodies:",
        "options": [
            {"label": "A", "text": "the total kinetic energy is conserved"},
            {"label": "B", "text": "the total potential energy is conserved"},
            {"label": "C", "text": "the linear momentum is not conserved"},
            {"label": "D", "text": "the linear momentum is conserved"}
        ],
        "correctAnswer": "D",
        "explanation": "In an inelastic collision, total linear momentum is always conserved because no external force acts on the system, but kinetic energy is lost as heat/deformation.",
        "questionType": "STATEMENT_BASED",
        "difficulty": "MEDIUM",
        "subject": "PHYSICS",
        "chapterBookCode": "keph105",
        "chapterTitle": "Work, Energy and Power",
        "sourceType": "PYQ",
        "examName": "AIIMS",
        "examYear": 2006,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "15",
        "sourceDocument": "AIIMS 2006 Solved Paper",
        "sourcePage": 2
    },
    {
        "id": "Q_PYQ_AIIMS_2007_PHY_007",
        "stem": "Three charged particles 1, 2 and 3 enter a uniform vertical electric field with equal horizontal velocities. Particle 3 shows maximum deflection towards the positive plate. Which particle has the highest charge-to-mass (q/m) ratio?",
        "options": [
            {"label": "A", "text": "Particle 1"},
            {"label": "B", "text": "Particle 2"},
            {"label": "C", "text": "Particle 3"},
            {"label": "D", "text": "All have the same ratio"}
        ],
        "correctAnswer": "C",
        "explanation": "Vertical displacement y = (1/2) a t² = (1/2) (qE/m) (L/vx)². Since E, L, and vx are constant, y ∝ (q/m). Maximum deflection corresponds to highest q/m.",
        "questionType": "DIAGRAM_BASED",
        "difficulty": "HARD",
        "subject": "PHYSICS",
        "chapterBookCode": "leph101",
        "chapterTitle": "Electric Charges and Fields",
        "sourceType": "PYQ",
        "examName": "AIIMS",
        "examYear": 2007,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "7",
        "sourceDocument": "AIIMS 2007 Solved Paper",
        "sourcePage": 1,
        "diagramPath": "/extracted_figures/aiims_2007_q7_electric_deflection.png"
    },
    {
        "id": "Q_PYQ_AIIMS_2007_PHY_042",
        "stem": "Assertion: At resonance, the inductive reactance equals capacitive reactance and the impedance of a series LCR circuit is minimum.\nReason: At resonance frequency, the power factor of a series LCR circuit becomes unity.",
        "options": [
            {"label": "A", "text": "Both assertion and reason are true and reason is the correct explanation of assertion"},
            {"label": "B", "text": "Both assertion and reason are true but reason is not the correct explanation of assertion"},
            {"label": "C", "text": "Assertion is true but reason is false"},
            {"label": "D", "text": "Both assertion and reason are false"}
        ],
        "correctAnswer": "B",
        "explanation": "At resonance XL = XC, so Z = R (minimum impedance). Power factor cos Φ = R/Z = R/R = 1. Both statements are true, but reason is a consequence, not explanation of Z = R.",
        "questionType": "ASSERTION_REASON",
        "difficulty": "HARD",
        "subject": "PHYSICS",
        "chapterBookCode": "leph107",
        "chapterTitle": "Alternating Current",
        "sourceType": "PYQ",
        "examName": "AIIMS",
        "examYear": 2007,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "42",
        "sourceDocument": "AIIMS 2007 Solved Paper",
        "sourcePage": 10
    },
    {
        "id": "Q_PYQ_AIPMT_2005_PHY_001",
        "stem": "A coil in the shape of an equilateral triangle of side l is suspended between the pole pieces of a permanent magnet such that B is in the plane of the coil. If due to a current i in the triangle a torque τ acts on it, the side l of the triangle is:",
        "options": [
            {"label": "A", "text": "2 (τ / √3 B i)^(1/2)"},
            {"label": "B", "text": "(2 / √3) (τ / B i)"},
            {"label": "C", "text": "2 (τ / B i)^(1/2)"},
            {"label": "D", "text": "1/2 (τ / B i)"}
        ],
        "correctAnswer": "A",
        "explanation": "Torque τ = NiAB sin 90° = 1 × i × (√3/4 l²) × B. Thus l² = 4τ / (√3 B i), giving l = 2 (τ / √3 B i)^(1/2).",
        "questionType": "NUMERICAL",
        "difficulty": "VERY_HARD",
        "subject": "PHYSICS",
        "chapterBookCode": "leph104",
        "chapterTitle": "Moving Charges and Magnetism",
        "sourceType": "PYQ",
        "examName": "AIPMT",
        "examYear": 2005,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "1",
        "sourceDocument": "AIPMT 2005 Prelims",
        "sourcePage": 1
    },

    # ==================== CHEMISTRY: REAL PYQ (7 Questions) ====================
    {
        "id": "Q_PYQ_NEET_2018_CHEM_083",
        "stem": "Which one of the following conditions will favour maximum formation of the product in the reaction:\nA₂(g) + B₂(g) ⇌ X₂(g), ΔrH = -X kJ?",
        "options": [
            {"label": "A", "text": "High temperature and high pressure"},
            {"label": "B", "text": "Low temperature and low pressure"},
            {"label": "C", "text": "Low temperature and high pressure"},
            {"label": "D", "text": "High temperature and low pressure"}
        ],
        "correctAnswer": "C",
        "explanation": "Reaction is exothermic (ΔH < 0), so low temperature favours forward reaction. Δng = 1 - (1 + 1) = -1 < 0 (decrease in moles), so high pressure shifts equilibrium forward by Le Chatelier's principle.",
        "questionType": "STATEMENT_BASED",
        "difficulty": "MEDIUM",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech106",
        "chapterTitle": "Equilibrium",
        "sourceType": "PYQ",
        "examName": "NEET",
        "examYear": 2018,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "83",
        "sourceDocument": "NEET (UG) 2018 Code AA",
        "sourcePage": 21
    },
    {
        "id": "Q_PYQ_NEET_2018_CHEM_085",
        "stem": "According to Molecular Orbital Theory, which of the following species has the highest bond order?",
        "options": [
            {"label": "A", "text": "CN⁻"},
            {"label": "B", "text": "NO"},
            {"label": "C", "text": "CN⁺"},
            {"label": "D", "text": "CN"}
        ],
        "correctAnswer": "A",
        "explanation": "Total electrons: CN⁻ has 14 electrons (isoelectronic with N₂). Bond order = (10 - 4)/2 = 3.0. NO has 15 electrons, bond order = 2.5.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "MEDIUM",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech104",
        "chapterTitle": "Chemical Bonding and Molecular Structure",
        "sourceType": "PYQ",
        "examName": "NEET",
        "examYear": 2018,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "85",
        "sourceDocument": "NEET (UG) 2018 Code AA",
        "sourcePage": 22
    },
    {
        "id": "Q_PYQ_AIPMT_2014_CHEM_064",
        "stem": "Be²⁺ is isoelectronic with which of the following ions?",
        "options": [
            {"label": "A", "text": "H⁺"},
            {"label": "B", "text": "Li⁺"},
            {"label": "C", "text": "Na⁺"},
            {"label": "D", "text": "Mg²⁺"}
        ],
        "correctAnswer": "B",
        "explanation": "Atomic number of Be is 4, so Be²⁺ has 4 - 2 = 2 electrons. Li has atomic number 3, so Li⁺ has 3 - 1 = 2 electrons. Both have 2 electrons.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "EASY",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech102",
        "chapterTitle": "Structure of Atom",
        "sourceType": "PYQ",
        "examName": "AIPMT",
        "examYear": 2014,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "64",
        "sourceDocument": "AIPMT 2014 Solved Paper",
        "sourcePage": 26
    },
    {
        "id": "Q_PYQ_AIPMT_2014_CHEM_065",
        "stem": "Which of the following molecules has the maximum dipole moment?",
        "options": [
            {"label": "A", "text": "CO₂"},
            {"label": "B", "text": "CH₄"},
            {"label": "C", "text": "NH₃"},
            {"label": "D", "text": "NF₃"}
        ],
        "correctAnswer": "C",
        "explanation": "CO₂ and CH₄ have μ = 0 due to symmetry. In NH₃, lone pair moment and N-H bond dipoles reinforce each other, whereas in NF₃ they oppose, making NH₃ have higher dipole moment (1.47 D vs 0.24 D).",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "MEDIUM",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech104",
        "chapterTitle": "Chemical Bonding and Molecular Structure",
        "sourceType": "PYQ",
        "examName": "AIPMT",
        "examYear": 2014,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "65",
        "sourceDocument": "AIPMT 2014 Solved Paper",
        "sourcePage": 26
    },
    {
        "id": "Q_PYQ_AIPMT_2014_CHEM_068",
        "stem": "Consider the reactions:\n(a) H₂O₂ + O₃ → H₂O + 2O₂\n(b) H₂O₂ + Ag₂O → 2Ag + H₂O + O₂\nRole of hydrogen peroxide in the above reactions is respectively:",
        "options": [
            {"label": "A", "text": "oxidizing in (a) and reducing in (b)"},
            {"label": "B", "text": "reducing in (a) and oxidizing in (b)"},
            {"label": "C", "text": "reducing in (a) and (b)"},
            {"label": "D", "text": "oxidizing in (a) and (b)"}
        ],
        "correctAnswer": "C",
        "explanation": "In (a), O₃ (0) is reduced to O₂ while H₂O₂ (-1) is oxidized to O₂ (0). In (b), Ag⁺ (+1) is reduced to Ag (0). Thus, H₂O₂ acts as a reducing agent in both reactions.",
        "questionType": "STATEMENT_BASED",
        "difficulty": "HARD",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech201",
        "chapterTitle": "Redox Reactions",
        "sourceType": "PYQ",
        "examName": "AIPMT",
        "examYear": 2014,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "68",
        "sourceDocument": "AIPMT 2014 Solved Paper",
        "sourcePage": 27
    },
    {
        "id": "Q_PYQ_AIIMS_2006_CHEM_045",
        "stem": "Ethanol boils at 78.4°C with enthalpy of vaporization ΔH_vap = 38.6 kJ/mol. The entropy of vaporization of ethanol is:",
        "options": [
            {"label": "A", "text": "109.8 J K⁻¹ mol⁻¹"},
            {"label": "B", "text": "492.3 J K⁻¹ mol⁻¹"},
            {"label": "C", "text": "55.4 J K⁻¹ mol⁻¹"},
            {"label": "D", "text": "220.1 J K⁻¹ mol⁻¹"}
        ],
        "correctAnswer": "A",
        "explanation": "T_b = 78.4 + 273.15 = 351.55 K. ΔS_vap = ΔH_vap / T_b = 38600 J/mol / 351.55 K = 109.8 J K⁻¹ mol⁻¹.",
        "questionType": "NUMERICAL",
        "difficulty": "MEDIUM",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech105",
        "chapterTitle": "Chemical Thermodynamics",
        "sourceType": "PYQ",
        "examName": "AIIMS",
        "examYear": 2006,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "45",
        "sourceDocument": "AIIMS 2006 Solved Paper",
        "sourcePage": 9
    },
    {
        "id": "Q_PYQ_AIIMS_2010_CHEM_055",
        "stem": "Assertion: [Fe(CN)₆]³⁻ is a low spin complex with one unpaired electron.\nReason: CN⁻ is a strong field ligand that causes pairing of 3d electrons of Fe³⁺.",
        "options": [
            {"label": "A", "text": "Both assertion and reason are true and reason is the correct explanation of assertion"},
            {"label": "B", "text": "Both assertion and reason are true but reason is not the correct explanation of assertion"},
            {"label": "C", "text": "Assertion is true but reason is false"},
            {"label": "D", "text": "Both assertion and reason are false"}
        ],
        "correctAnswer": "A",
        "explanation": "Fe³⁺ has 3d⁵ configuration. CN⁻ is a strong field ligand (high Δo), causing pairing into t₂g⁵ eg⁰, leaving 1 unpaired electron (low spin d²sp³ complex).",
        "questionType": "ASSERTION_REASON",
        "difficulty": "HARD",
        "subject": "CHEMISTRY",
        "chapterBookCode": "lech105",
        "chapterTitle": "Coordination Compounds",
        "sourceType": "PYQ",
        "examName": "AIIMS",
        "examYear": 2010,
        "yearConfidence": 1.0,
        "yearSource": "EXPLICIT_HEADER",
        "originalQuestionNumber": "55",
        "sourceDocument": "AIIMS 2010 Solved Paper",
        "sourcePage": 14
    },

    # ==================== MTG FINGERTIPS: BIOLOGY (10 Questions) ====================
    {
        "id": "Q_FT_MTG_BIO_CH1_001",
        "stem": "As we go from species to kingdom in a taxonomic hierarchy, the number of common characteristics:",
        "options": [
            {"label": "A", "text": "will decrease"},
            {"label": "B", "text": "will increase"},
            {"label": "C", "text": "remain same"},
            {"label": "D", "text": "may increase or decrease"}
        ],
        "correctAnswer": "A",
        "explanation": "Lower the taxon, more are the common characteristics that members share. As we move upward from species to kingdom, general characteristics increase while common characteristics decrease.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "EASY",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo101",
        "chapterTitle": "The Living World",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Biology",
        "bookEdition": "2026",
        "originalQuestionNumber": "1",
        "sourceDocument": "MTG Fingertips Biology 2026 Ch 1",
        "sourcePage": 32
    },
    {
        "id": "Q_FT_MTG_BIO_CH1_002",
        "stem": "Which of the following suffixes used for units of classification in plants indicates a taxonomic category of 'family'?",
        "options": [
            {"label": "A", "text": "— ales"},
            {"label": "B", "text": "— onae"},
            {"label": "C", "text": "— aceae"},
            {"label": "D", "text": "— ae"}
        ],
        "correctAnswer": "C",
        "explanation": "In plant taxonomy, the suffix '-aceae' is used for family (e.g. Solanaceae, Poaceae). '-ales' is used for order (e.g. Polymoniales).",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "EASY",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo101",
        "chapterTitle": "The Living World",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Biology",
        "bookEdition": "2026",
        "originalQuestionNumber": "2",
        "sourceDocument": "MTG Fingertips Biology 2026 Ch 1",
        "sourcePage": 32
    },
    {
        "id": "Q_FT_MTG_BIO_CH1_003",
        "stem": "The term 'systematics' refers to:",
        "options": [
            {"label": "A", "text": "identification and study of organ systems"},
            {"label": "B", "text": "identification and preservation of plants and animals"},
            {"label": "C", "text": "diversity of kinds of organisms and their comparative and evolutionary relationships"},
            {"label": "D", "text": "study of habitats of organisms and their classification"}
        ],
        "correctAnswer": "C",
        "explanation": "Systematics takes into account evolutionary relationships between organisms along with morphological and taxonomic diversity.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "MEDIUM",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo101",
        "chapterTitle": "The Living World",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Biology",
        "bookEdition": "2026",
        "originalQuestionNumber": "3",
        "sourceDocument": "MTG Fingertips Biology 2026 Ch 1",
        "sourcePage": 32
    },
    {
        "id": "Q_FT_MTG_BIO_CH1_004",
        "stem": "Genus represents:",
        "options": [
            {"label": "A", "text": "an individual plant or animal"},
            {"label": "B", "text": "a collection of plants or animals"},
            {"label": "C", "text": "group of closely related species of plants or animals"},
            {"label": "D", "text": "none of these"}
        ],
        "correctAnswer": "C",
        "explanation": "Genus comprises a group of related species which has more characters in common in comparison to species of other genera.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "EASY",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo101",
        "chapterTitle": "The Living World",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Biology",
        "bookEdition": "2026",
        "originalQuestionNumber": "4",
        "sourceDocument": "MTG Fingertips Biology 2026 Ch 1",
        "sourcePage": 32
    },
    {
        "id": "Q_FT_MTG_BIO_CH1_005",
        "stem": "The taxonomic unit 'Phylum' in the classification of animals is equivalent to which hierarchical level in classification of plants?",
        "options": [
            {"label": "A", "text": "Class"},
            {"label": "B", "text": "Order"},
            {"label": "C", "text": "Division"},
            {"label": "D", "text": "Family"}
        ],
        "correctAnswer": "C",
        "explanation": "In plant classification, the category 'Division' is used instead of 'Phylum' used for animals.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "EASY",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo101",
        "chapterTitle": "The Living World",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Biology",
        "bookEdition": "2026",
        "originalQuestionNumber": "5",
        "sourceDocument": "MTG Fingertips Biology 2026 Ch 1",
        "sourcePage": 32
    },
    {
        "id": "Q_FT_MTG_BIO_CH1_006",
        "stem": "Match column I with column II and choose the correct option:\nColumn I:\nA. Family\nB. Kingdom\nC. Order\nD. Species\nE. Genus\nColumn II:\ni. tuberosum\nii. Polymoniales\niii. Solanum\niv. Plantae\nv. Solanaceae",
        "options": [
            {"label": "A", "text": "A-v, B-iv, C-ii, D-i, E-iii"},
            {"label": "B", "text": "A-iv, B-iii, C-v, D-ii, E-i"},
            {"label": "C", "text": "A-v, B-iv, C-i, D-ii, E-iii"},
            {"label": "D", "text": "A-ii, B-iv, C-v, D-iii, E-i"}
        ],
        "correctAnswer": "A",
        "explanation": "Family: Solanaceae (v); Kingdom: Plantae (iv); Order: Polymoniales (ii); Species: tuberosum (i); Genus: Solanum (iii).",
        "questionType": "MATCHING",
        "difficulty": "MEDIUM",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo101",
        "chapterTitle": "The Living World",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Biology",
        "bookEdition": "2026",
        "originalQuestionNumber": "6",
        "sourceDocument": "MTG Fingertips Biology 2026 Ch 1",
        "sourcePage": 32
    },
    {
        "id": "Q_FT_MTG_BIO_CH1_AR1",
        "stem": "Assertion: Binomial nomenclature is needed for all living organisms.\nReason: A particular organism is known by the same scientific name all over the world in binomial nomenclature.",
        "options": [
            {"label": "A", "text": "Both assertion and reason are true and reason is the correct explanation of assertion"},
            {"label": "B", "text": "Both assertion and reason are true but reason is not the correct explanation of assertion"},
            {"label": "C", "text": "Assertion is true but reason is false"},
            {"label": "D", "text": "Both assertion and reason are false"}
        ],
        "correctAnswer": "A",
        "explanation": "Binomial nomenclature provides a standardized international name to avoid confusion caused by local vernacular names.",
        "questionType": "ASSERTION_REASON",
        "difficulty": "MEDIUM",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo101",
        "chapterTitle": "The Living World",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Biology",
        "bookEdition": "2026",
        "originalQuestionNumber": "AR-1",
        "sourceDocument": "MTG Fingertips Biology 2026 Ch 1",
        "sourcePage": 32
    },
    {
        "id": "Q_FT_MTG_BIO_CH1_CASE1",
        "stem": "Hierarchy of categories is the classification of organisms in a definite sequence of categories called taxonomic categories. First proposed by Linnaeus, the arrangement depicts taxa in ascending order from species to kingdom. Which category comprises an assemblage of families exhibiting a few common floral characters?",
        "options": [
            {"label": "A", "text": "Class"},
            {"label": "B", "text": "Order"},
            {"label": "C", "text": "Division"},
            {"label": "D", "text": "Genus"}
        ],
        "correctAnswer": "B",
        "explanation": "Order is an assemblage of related families exhibiting fewer similarities than families (e.g. Convolvulaceae and Solanaceae in Polymoniales).",
        "questionType": "PASSAGE",
        "difficulty": "HARD",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo101",
        "chapterTitle": "The Living World",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Biology",
        "bookEdition": "2026",
        "originalQuestionNumber": "Case-1",
        "sourceDocument": "MTG Fingertips Biology 2026 Ch 1",
        "sourcePage": 34
    },
    {
        "id": "Q_FT_MTG_BIO_CH1_DIAG1",
        "stem": "Identify A, B, and C in the given ascending taxonomic hierarchy flowchart: Species → C → Family → B → Class → A → Kingdom.",
        "options": [
            {"label": "A", "text": "A — Order, B — Division, C — Genus"},
            {"label": "B", "text": "A — Phylum, B — Order, C — Genus"},
            {"label": "C", "text": "A — Genus, B — Phylum, C — Division"},
            {"label": "D", "text": "A — Phylum, B — Genus, C — Order"}
        ],
        "correctAnswer": "B",
        "explanation": "Ascending order: Species → Genus (C) → Family → Order (B) → Class → Phylum/Division (A) → Kingdom.",
        "questionType": "DIAGRAM_BASED",
        "difficulty": "MEDIUM",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo101",
        "chapterTitle": "The Living World",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Biology",
        "bookEdition": "2026",
        "originalQuestionNumber": "Diag-1",
        "sourceDocument": "MTG Fingertips Biology 2026 Ch 1",
        "sourcePage": 34,
        "diagramPath": "/extracted_figures/mtg_bio_ch1_taxonomic_hierarchy.png"
    },
    {
        "id": "Q_FT_MTG_BIO_CH1_012_DUP",
        "stem": "The common characteristics between tomato and potato will be maximum at the level of their:",
        "options": [
            {"label": "A", "text": "family"},
            {"label": "B", "text": "order"},
            {"label": "C", "text": "division"},
            {"label": "D", "text": "genus"}
        ],
        "correctAnswer": "A",
        "explanation": "Tomato (Lycopersicon esculentum) and Potato (Solanum tuberosum) belong to different genera under the common family Solanaceae.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "MEDIUM",
        "subject": "BIOLOGY",
        "chapterBookCode": "kebo101",
        "chapterTitle": "The Living World",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Biology",
        "bookEdition": "2026",
        "originalQuestionNumber": "12",
        "sourceDocument": "MTG Fingertips Biology 2026 Ch 1",
        "sourcePage": 38
    },

    # ==================== MTG FINGERTIPS: PHYSICS (5 Questions) ====================
    {
        "id": "Q_FT_MTG_PHY_CH1_001",
        "stem": "The dimensional formula of Planck's constant (h) is identical to that of:",
        "options": [
            {"label": "A", "text": "Linear momentum"},
            {"label": "B", "text": "Angular momentum"},
            {"label": "C", "text": "Work"},
            {"label": "D", "text": "Power"}
        ],
        "correctAnswer": "B",
        "explanation": "Planck's constant h = E / ν = [M L² T⁻²] / [T⁻¹] = [M L² T⁻¹]. Angular momentum L = mvr = [M] [L T⁻¹] [L] = [M L² T⁻¹].",
        "questionType": "NUMERICAL",
        "difficulty": "EASY",
        "subject": "PHYSICS",
        "chapterBookCode": "keph101",
        "chapterTitle": "Units and Measurements",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Physics",
        "bookEdition": "2026",
        "originalQuestionNumber": "1",
        "sourceDocument": "MTG Fingertips Physics 2026 Ch 1",
        "sourcePage": 10
    },
    {
        "id": "Q_FT_MTG_PHY_CH1_004",
        "stem": "The mass and volume of a body are measured as 22.42 g and 4.7 cm³. The density of the body up to correct significant figures is:",
        "options": [
            {"label": "A", "text": "4.77 g/cm³"},
            {"label": "B", "text": "4.8 g/cm³"},
            {"label": "C", "text": "4.770 g/cm³"},
            {"label": "D", "text": "4.7702 g/cm³"}
        ],
        "correctAnswer": "B",
        "explanation": "Density = 22.42 / 4.7 = 4.7702... Since volume has 2 significant figures, the result must be rounded off to 2 significant figures, giving 4.8 g/cm³.",
        "questionType": "NUMERICAL",
        "difficulty": "MEDIUM",
        "subject": "PHYSICS",
        "chapterBookCode": "keph101",
        "chapterTitle": "Units and Measurements",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Physics",
        "bookEdition": "2026",
        "originalQuestionNumber": "4",
        "sourceDocument": "MTG Fingertips Physics 2026 Ch 1",
        "sourcePage": 11
    },
    {
        "id": "Q_FT_MTG_PHY_CH4_012",
        "stem": "A block of mass m rests on a rough inclined plane making an angle θ with the horizontal. If the coefficient of static friction is μ, the maximum angle of inclination for which the block does not slide down is:",
        "options": [
            {"label": "A", "text": "θ = tan⁻¹(μ)"},
            {"label": "B", "text": "θ = sin⁻¹(μ)"},
            {"label": "C", "text": "θ = cos⁻¹(μ)"},
            {"label": "D", "text": "θ = tan⁻¹(1/μ)"}
        ],
        "correctAnswer": "A",
        "explanation": "At the verge of sliding, mg sin θ = μ mg cos θ, which yields tan θ = μ, so θ = tan⁻¹(μ) (angle of repose).",
        "questionType": "STATEMENT_BASED",
        "difficulty": "EASY",
        "subject": "PHYSICS",
        "chapterBookCode": "keph104",
        "chapterTitle": "Laws of Motion",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Physics",
        "bookEdition": "2026",
        "originalQuestionNumber": "12",
        "sourceDocument": "MTG Fingertips Physics 2026 Ch 4",
        "sourcePage": 65
    },
    {
        "id": "Q_FT_MTG_PHY_CH4_AR1",
        "stem": "Assertion: Rocket propulsion is an application of Newton's third law of motion.\nReason: The exhaust gases pushed backward exert an equal and opposite forward thrust on the rocket.",
        "options": [
            {"label": "A", "text": "Both assertion and reason are true and reason is the correct explanation of assertion"},
            {"label": "B", "text": "Both assertion and reason are true but reason is not the correct explanation of assertion"},
            {"label": "C", "text": "Assertion is true but reason is false"},
            {"label": "D", "text": "Both assertion and reason are false"}
        ],
        "correctAnswer": "A",
        "explanation": "Rocket engines expel high velocity gases backwards (action), and by Newton's third law, the gases impart an equal forward reaction impulse to accelerate the rocket.",
        "questionType": "ASSERTION_REASON",
        "difficulty": "MEDIUM",
        "subject": "PHYSICS",
        "chapterBookCode": "keph104",
        "chapterTitle": "Laws of Motion",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Physics",
        "bookEdition": "2026",
        "originalQuestionNumber": "AR-1",
        "sourceDocument": "MTG Fingertips Physics 2026 Ch 4",
        "sourcePage": 70
    },
    {
        "id": "Q_FT_MTG_PHY_CH4_DIAG1",
        "stem": "Two masses m₁ = 4 kg and m₂ = 6 kg are connected by a light inextensible string passing over a frictionless pulley. What is the tension in the string when released from rest?",
        "options": [
            {"label": "A", "text": "47 N"},
            {"label": "B", "text": "24 N"},
            {"label": "C", "text": "48 N"},
            {"label": "D", "text": "58.8 N"}
        ],
        "correctAnswer": "A",
        "explanation": "T = 2 m₁ m₂ g / (m₁ + m₂) = 2(4)(6)(9.8) / (10) = 47.04 N ≈ 47 N.",
        "questionType": "DIAGRAM_BASED",
        "difficulty": "HARD",
        "subject": "PHYSICS",
        "chapterBookCode": "keph104",
        "chapterTitle": "Laws of Motion",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Physics",
        "bookEdition": "2026",
        "originalQuestionNumber": "Diag-1",
        "sourceDocument": "MTG Fingertips Physics 2026 Ch 4",
        "sourcePage": 72,
        "diagramPath": "/extracted_figures/mtg_phy_ch4_atwood_pulley.png"
    },

    # ==================== MTG FINGERTIPS: CHEMISTRY (9 Questions) ====================
    {
        "id": "Q_FT_MTG_CHEM_CH1_008",
        "stem": "Which of the following contains the greatest number of atoms?",
        "options": [
            {"label": "A", "text": "1.0 g of butane (C₄H₁₀)"},
            {"label": "B", "text": "1.0 g of nitrogen (N₂)"},
            {"label": "C", "text": "1.0 g of silver (Ag)"},
            {"label": "D", "text": "1.0 g of water (H₂O)"}
        ],
        "correctAnswer": "D",
        "explanation": "Number of atoms = (mass/molar mass) × atoms per molecule × N_A. For H₂O: (1/18) × 3 × N_A = 0.166 N_A. For C₄H₁₀: (1/58) × 14 × N_A = 0.241 N_A... Wait: (14/58) = 0.241 N_A > (3/18) = 0.166 N_A. But in butane: 14/58 = 0.2413. Wait, in butane it is 0.241 N_A, making C₄H₁₀ greatest! Wait, option D in textbook answer key: Water has 3 atoms/18g = 1/6 NA = 0.166 NA. But 1g of H2O vs 1g C4H10: 14/58 = 0.241 NA.",
        "correctAnswer": "A",
        "explanation": "Total atoms = (m/M) × n_atoms × N_A. In 1.0 g butane (C₄H₁₀): (1/58) × 14 × N_A = 0.241 N_A, which is greater than (3/18) × N_A = 0.167 N_A for H₂O.",
        "questionType": "NUMERICAL",
        "difficulty": "HARD",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech101",
        "chapterTitle": "Some Basic Concepts of Chemistry",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Chemistry",
        "bookEdition": "2026",
        "originalQuestionNumber": "8",
        "sourceDocument": "MTG Fingertips Chemistry 2026 Ch 1",
        "sourcePage": 15
    },
    {
        "id": "Q_FT_MTG_CHEM_CH1_015",
        "stem": "A compound contains 4.07% hydrogen, 24.27% carbon and 71.65% chlorine. Its molar mass is 98.96 g. Its empirical formula is:",
        "options": [
            {"label": "A", "text": "CH₂Cl"},
            {"label": "B", "text": "CHCl"},
            {"label": "C", "text": "CH₃Cl"},
            {"label": "D", "text": "C₂H₄Cl₂"}
        ],
        "correctAnswer": "A",
        "explanation": "Moles of C = 24.27/12 = 2.02; Moles of H = 4.07/1 = 4.07; Moles of Cl = 71.65/35.5 = 2.02. Ratio C:H:Cl = 1:2:1. Empirical formula = CH₂Cl.",
        "questionType": "NUMERICAL",
        "difficulty": "MEDIUM",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech101",
        "chapterTitle": "Some Basic Concepts of Chemistry",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Chemistry",
        "bookEdition": "2026",
        "originalQuestionNumber": "15",
        "sourceDocument": "MTG Fingertips Chemistry 2026 Ch 1",
        "sourcePage": 18
    },
    {
        "id": "Q_FT_MTG_CHEM_CH4_022",
        "stem": "According to VSEPR theory, the molecular shapes of SF₄ and XeF₄ are respectively:",
        "options": [
            {"label": "A", "text": "See-saw and square planar"},
            {"label": "B", "text": "Tetrahedral and see-saw"},
            {"label": "C", "text": "Square planar and see-saw"},
            {"label": "D", "text": "See-saw and tetrahedral"}
        ],
        "correctAnswer": "A",
        "explanation": "SF₄ has 4 bond pairs and 1 lone pair (sp³d, see-saw shape). XeF₄ has 4 bond pairs and 2 lone pairs (sp³d², square planar geometry).",
        "questionType": "STATEMENT_BASED",
        "difficulty": "MEDIUM",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech104",
        "chapterTitle": "Chemical Bonding and Molecular Structure",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Chemistry",
        "bookEdition": "2026",
        "originalQuestionNumber": "22",
        "sourceDocument": "MTG Fingertips Chemistry 2026 Ch 4",
        "sourcePage": 52
    },
    {
        "id": "Q_FT_MTG_CHEM_CH4_AR1",
        "stem": "Assertion: The boiling point of HF is significantly higher than that of HCl.\nReason: HF molecules participate in strong intermolecular hydrogen bonding due to high electronegativity of fluorine.",
        "options": [
            {"label": "A", "text": "Both assertion and reason are true and reason is the correct explanation of assertion"},
            {"label": "B", "text": "Both assertion and reason are true but reason is not the correct explanation of assertion"},
            {"label": "C", "text": "Assertion is true but reason is false"},
            {"label": "D", "text": "Both assertion and reason are false"}
        ],
        "correctAnswer": "A",
        "explanation": "Fluorine is the most electronegative element, resulting in strong intermolecular hydrogen bonds in HF that require high thermal energy to dissociate.",
        "questionType": "ASSERTION_REASON",
        "difficulty": "EASY",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech104",
        "chapterTitle": "Chemical Bonding and Molecular Structure",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Chemistry",
        "bookEdition": "2026",
        "originalQuestionNumber": "AR-1",
        "sourceDocument": "MTG Fingertips Chemistry 2026 Ch 4",
        "sourcePage": 58
    },
    {
        "id": "Q_FT_MTG_CHEM_CH7_010",
        "stem": "The oxidation numbers of chromium in K₂Cr₂O₇ and CrO₅ (butterfly structure) are respectively:",
        "options": [
            {"label": "A", "text": "+6 and +6"},
            {"label": "B", "text": "+6 and +10"},
            {"label": "C", "text": "+6 and +4"},
            {"label": "D", "text": "+3 and +6"}
        ],
        "correctAnswer": "A",
        "explanation": "In K₂Cr₂O₇, 2(+1) + 2x + 7(-2) = 0 ⇒ x = +6. In CrO₅, Cr has one oxo oxygen (=O, -2) and two peroxo bridges (-O-O-, four oxygens at -1 each). x + (-2) + 4(-1) = 0 ⇒ x = +6.",
        "questionType": "NUMERICAL",
        "difficulty": "HARD",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech201",
        "chapterTitle": "Redox Reactions",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Chemistry",
        "bookEdition": "2026",
        "originalQuestionNumber": "10",
        "sourceDocument": "MTG Fingertips Chemistry 2026 Ch 7",
        "sourcePage": 92
    },
    {
        "id": "Q_FT_MTG_CHEM_CH8_004",
        "stem": "In the Lassaigne's test for detection of nitrogen in an organic compound, the Prussian blue colour is due to the formation of:",
        "options": [
            {"label": "A", "text": "Fe₄[Fe(CN)₆]₃"},
            {"label": "B", "text": "Fe₃[Fe(CN)₆]₂"},
            {"label": "C", "text": "Na₄[Fe(CN)₆]"},
            {"label": "D", "text": "Fe(CNS)₃"}
        ],
        "correctAnswer": "A",
        "explanation": "Ferriferrocyanide (Prussian blue), Fe₄[Fe(CN)₆]₃, is formed when sodium cyanide extract reacts with ferrous sulfate and ferric chloride.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "MEDIUM",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech202",
        "chapterTitle": "Organic Chemistry – Some Basic Principles and Techniques",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Chemistry",
        "bookEdition": "2026",
        "originalQuestionNumber": "4",
        "sourceDocument": "MTG Fingertips Chemistry 2026 Ch 8",
        "sourcePage": 110
    },
    {
        "id": "Q_FT_MTG_CHEM_CH8_012",
        "stem": "The correct order of stability of carbocations is:",
        "options": [
            {"label": "A", "text": "(CH₃)₃C⁺ > (CH₃)₂CH⁺ > CH₃CH₂⁺ > CH₃⁺"},
            {"label": "B", "text": "CH₃⁺ > CH₃CH₂⁺ > (CH₃)₂CH⁺ > (CH₃)₃C⁺"},
            {"label": "C", "text": "(CH₃)₂CH⁺ > (CH₃)₃C⁺ > CH₃CH₂⁺ > CH₃⁺"},
            {"label": "D", "text": "(CH₃)₃C⁺ > CH₃CH₂⁺ > (CH₃)₂CH⁺ > CH₃⁺"}
        ],
        "correctAnswer": "A",
        "explanation": "Tertiary carbocation (9 hyperconjugative α-hydrogens) > Secondary (6) > Primary (3) > Methyl (0) due to inductive effect and hyperconjugation.",
        "questionType": "STATEMENT_BASED",
        "difficulty": "EASY",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech202",
        "chapterTitle": "Organic Chemistry – Some Basic Principles and Techniques",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Chemistry",
        "bookEdition": "2026",
        "originalQuestionNumber": "12",
        "sourceDocument": "MTG Fingertips Chemistry 2026 Ch 8",
        "sourcePage": 114
    },
    {
        "id": "Q_FT_MTG_CHEM_CH9_008",
        "stem": "Ozonolysis of 2,3-dimethyl-2-butene followed by Zn/H₂O cleavage yields:",
        "options": [
            {"label": "A", "text": "Two molecules of acetone"},
            {"label": "B", "text": "One molecule of acetaldehyde and one of acetone"},
            {"label": "C", "text": "Two molecules of acetaldehyde"},
            {"label": "D", "text": "Acetic acid and propionic acid"}
        ],
        "correctAnswer": "A",
        "explanation": "Cleavage of the double bond (CH₃)₂C=C(CH₃)₂ with ozone and zinc reduction produces two symmetrical molecules of propan-2-one (acetone).",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "MEDIUM",
        "subject": "CHEMISTRY",
        "chapterBookCode": "kech203",
        "chapterTitle": "Hydrocarbons",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Chemistry",
        "bookEdition": "2026",
        "originalQuestionNumber": "8",
        "sourceDocument": "MTG Fingertips Chemistry 2026 Ch 9",
        "sourcePage": 132
    },
    {
        "id": "Q_FT_MTG_CHEM_CH6_020",
        "stem": "In the reaction of chlorobenzene with chloromethane in the presence of anhydrous AlCl₃ (Friedel-Crafts alkylation), the major product is:",
        "options": [
            {"label": "A", "text": "1-chloro-4-methylbenzene (p-chlorotoluene)"},
            {"label": "B", "text": "1-chloro-2-methylbenzene (o-chlorotoluene)"},
            {"label": "C", "text": "1-chloro-3-methylbenzene (m-chlorotoluene)"},
            {"label": "D", "text": "Toluene"}
        ],
        "correctAnswer": "A",
        "explanation": "Chlorine is ortho/para-directing due to resonance (+M effect). Para-product dominates due to minimum steric hindrance.",
        "questionType": "SINGLE_CORRECT",
        "difficulty": "MEDIUM",
        "subject": "CHEMISTRY",
        "chapterBookCode": "lech201",
        "chapterTitle": "Haloalkanes and Haloarenes",
        "sourceType": "FINGERTIPS",
        "bookName": "MTG Objective NCERT at your Fingertips - Chemistry",
        "bookEdition": "2026",
        "originalQuestionNumber": "20",
        "sourceDocument": "MTG Fingertips Chemistry 2026 Ch 6",
        "sourcePage": 88
    }
]
