"""
Generate docs/MTG_INTEGRATION.md (spec §34 item 11 — Documentation).

Integration documentation explaining:
  - Canonical source state
  - Mapping registry
  - Sequence validation
  - Review queue
  - Migration procedure (DB integration plan)
  - Frontend integration status
  - Idempotency
  - Validation commands
"""
import json, os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
DOCS = os.path.join(ROOT, 'docs')

def load(p):
    with open(p,'r',encoding='utf-8') as f: return json.load(f)

mapping   = load(os.path.join(DOCS,'MTG_NCERT_TOPIC_MAPPING.json'))
seq       = load(os.path.join(DOCS,'MTG_SEQUENCE_VALIDATION.json'))
rq        = load(os.path.join(DOCS,'MTG_UNMAPPED_REVIEW_QUEUE.json'))
manifest  = load(os.path.join(DOCS,'MTG_SOURCE_MASTER_MANIFEST.json'))
inventory = load(os.path.join(DOCS,'MTG_AUTHORITATIVE_SOURCE_INVENTORY.json'))
audit     = load(os.path.join(DOCS,'MTG_EXAM_SCORER_AUDIT_RESULT.json'))

lines = []
lines.append("# MTG Fingertips → EKriti NCERT Topic Integration — Documentation")
lines.append("")
lines.append("**Spec**: 35-section MTG Fingertips → EKriti NCERT Topic Integration")
lines.append("**Generated**: 2026-10-05")
lines.append("")
lines.append("This document is the integration guide for connecting the canonical MTG")
lines.append("Fingertips question dataset to the EKriti NCERT topic hierarchy. It is")
lines.append("intended to be read alongside the audit report (`docs/MTG_NCERT_INTEGRATION_AUDIT.md`)")
lines.append("and the deterministic mapping registry (`docs/MTG_NCERT_TOPIC_MAPPING.json`).")
lines.append("")
lines.append("---")
lines.append("")

# 1. Overview
lines.append("## 1. Overview")
lines.append("")
lines.append("The MTG → NCERT integration is structured as two strictly-separated layers")
lines.append("per spec §7:")
lines.append("")
lines.append("```")
lines.append("CHAPTER")
lines.append("├── TOPIC_DRILL       (1.1, 1.2, 1.3, ...)")
lines.append("│   Each topic maps to exactly ONE NCERT topic.")
lines.append("│   Questions preserve source ordering via SHA-256 sequence hash.")
lines.append("└── EXAM_SCORER       (chapter-level)")
lines.append("    Subsections: EXEMPLAR / ASSERTION_REASON / STATEMENT_BASED /")
lines.append("                MATCHING_BASED / CORE / CASE_BASED / FIGURE_BASED /")
lines.append("                MULTIDIMENSIONAL / EXAM_ARCHIVE / THINKING_CORNER /")
lines.append("                + any other source-defined subsection (per spec §23)")
lines.append("```")
lines.append("")
lines.append("Per spec §1, §4, §11: TOPIC_DRILL and EXAM_SCORER must NEVER be merged.")
lines.append("Exam Scorer questions must NEVER be attached to a numbered NCERT topic.")
lines.append("")
lines.append("---")
lines.append("")

# 2. Canonical source state
lines.append("## 2. Canonical Source State")
lines.append("")
lines.append("The canonical MTG source is documented in three repo-resident artifacts:")
lines.append("")
lines.append("| Artifact | Purpose | Records |")
lines.append("|---|---|---|")
lines.append(f"| `docs/MTG_AUTHORITATIVE_SOURCE_INVENTORY.json` | Master chapter-level inventory | 79 in-syllabus chapters across BIO/CHE/PHY × Class 11+12 |")
lines.append(f"| `docs/MTG_SOURCE_MASTER_MANIFEST.json` | Verbatim canonical manifest (with fingerprints) | {len(manifest['questions'])} questions |")
lines.append(f"| `src/lib/auditor/canonical_topic_registry.py` | NCERT topic registry | 79 chapters × 302 topics |")
lines.append("")
lines.append("**Source PDFs** (per `MTG_AUTHORITATIVE_SOURCE_INVENTORY.json`):")
lines.append("")
lines.append("| Subject | File | Pages |")
lines.append("|---|---|---|")
sf = inventory['sourceFiles']
for s in ['BIOLOGY','CHEMISTRY','PHYSICS']:
    f = sf.get(s, {})
    lines.append(f"| {s.title()} | {f.get('file','?')} | {f.get('pages','?')} |")
lines.append("")
lines.append("**Source location**: Google Drive folder ID `1X9uI9yRlzY4itV7mVdLt6xVlKv_gQjdN`")
lines.append("(per `MTG_AUTHORITATIVE_SOURCE_INVENTORY.json -> metadata.sourceLocation`)")
lines.append("")
lines.append("### 2.1 Canonical accounting")
lines.append("")
lines.append("Per `MTG_AUTHORITATIVE_SOURCE_INVENTORY.json -> metadata.summary`:")
lines.append("")
lines.append(f"- **Total source MCQs**: {inventory['metadata']['summary']['totalSourceMCQs']}")
lines.append(f"- **Total deployed MCQs** (DB rows, including synthetic): {inventory['metadata']['summary']['totalDeployedMCQs']}")
lines.append(f"- **Total in-syllabus chapters**: {inventory['metadata']['summary']['totalInSyllabusChapters']}")
lines.append(f"- **Total out-of-syllabus chapters** (filtered out): {inventory['metadata']['summary']['totalOutOfSyllabusChapters']}")
lines.append("")
lines.append("### 2.2 Verbatim content gap")
lines.append("")
lines.append("Per `MTG_EXAM_SCORER_AUDIT_RESULT.json -> globalMetrics`:")
lines.append("")
lines.append(f"- **AUTHENTIC_EXACT_MATCH**: {audit['classificationDistribution'].get('AUTHENTIC_EXACT_MATCH', 0)}")
lines.append(f"- **SUSPECTED_SYNTHETIC_GLOBAL**: {audit['classificationDistribution'].get('SUSPECTED_SYNTHETIC_GLOBAL', 0)}")
lines.append(f"- **SUSPECTED_SYNTHETIC**: {audit['classificationDistribution'].get('SUSPECTED_SYNTHETIC', 0)}")
lines.append("")
lines.append(f"Only `{audit['globalMetrics']['authenticTotalMCQs']}` of the")
lines.append(f"`{audit['globalMetrics']['applicationTotalMCQs']}` DB rows have question text")
lines.append("that exactly matches the canonical source. The remaining")
lines.append(f"`{audit['globalMetrics']['syntheticTotalMCQs']}` rows have placeholder/synthetic")
lines.append("question text and must be back-filled with authentic source content.")
lines.append("")
lines.append("---")
lines.append("")

# 3. Mapping registry
lines.append("## 3. Mapping Registry")
lines.append("")
lines.append(f"File: `docs/MTG_NCERT_TOPIC_MAPPING.json` — {len(mapping['records'])} records")
lines.append("")
lines.append("Each record follows spec §9 schema:")
lines.append("")
lines.append("```")
lines.append("{")
lines.append('  "NCERT_TOPIC_ID":        "PHY11-CH01-T01",')
lines.append('  "SUBJECT":               "Physics",')
lines.append('  "CLASS":                 "Class 11",')
lines.append('  "CHAPTER_ID":            "<cuid>",')
lines.append('  "CHAPTER_NUMBER":        1,')
lines.append('  "CHAPTER_NAME":          "Units and Measurements",')
lines.append('  "NCERT_TOPIC_NUMBER":    "1.1",')
lines.append('  "NCERT_TOPIC_NAME":      "<exact registry title>",')
lines.append('  "MTG_TOPIC_NUMBER":      "1.1",')
lines.append('  "MTG_TOPIC_NAME":        "<exact registry title>",')
lines.append('  "MTG_QUESTION_COUNT":    N,')
lines.append('  "MAPPED_QUESTION_IDS":   ["Q_FT_MTG_KEPH101_T1_1_01", ...],')
lines.append('  "SEQUENCE_HASH":         "<sha256 of source_id_1|source_id_2|...>",')
lines.append('  "MAPPING_STATUS":        "VERIFIED" | "PENDING_SOURCE_BACKFILL"')
lines.append('  "EXAM_SCORER_TYPE"?:     "ASSERTION_REASON" | "EXAM_ARCHIVE" | ...')
lines.append("}")
lines.append("```")
lines.append("")
lines.append(f"- {sum(1 for r in mapping['records'] if r['MAPPING_STATUS']=='VERIFIED')} records VERIFIED")
lines.append(f"- {sum(1 for r in mapping['records'] if r['MAPPING_STATUS']=='PENDING_SOURCE_BACKFILL')} records PENDING_SOURCE_BACKFILL")
lines.append("")
lines.append("### 3.1 Topic-drill vs exam-scorer separation")
lines.append("")
lines.append("Records WITHOUT `EXAM_SCORER_TYPE` field = topic-drill.")
lines.append("Records WITH `EXAM_SCORER_TYPE` field = exam-scorer pseudo-topic.")
lines.append("")
lines.append("The two layers are never merged in the registry, in the JSON manifest, or")
lines.append("in the application schema (per spec §4).")
lines.append("")
lines.append("---")
lines.append("")

# 4. Sequence validation
lines.append("## 4. Sequence Validation (SHA-256 per Topic)")
lines.append("")
lines.append(f"File: `docs/MTG_SEQUENCE_VALIDATION.json` — {len(seq['records'])} records")
lines.append("")
lines.append("Per spec §21, every topic with questions has a deterministic SHA-256")
lines.append("sequence fingerprint computed over the ordered concatenation of source_ids:")
lines.append("")
lines.append("```python")
lines.append("import hashlib")
lines.append("h = hashlib.sha256()")
lines.append("for q in questions_in_topic_in_source_order:")
lines.append("    h.update(q['source_id'].encode()); h.update(b'|')")
lines.append("canonical_sequence_hash = h.hexdigest()")
lines.append("```")
lines.append("")
lines.append("After DB migration, the post-migration validator computes the same hash from")
lines.append("the application's `Question` rows ordered by `originalQuestionNumber` within")
lines.append("each `Topic`. The two hashes MUST match (per spec §21).")
lines.append("")
lines.append("Current state:")
lines.append("")
lines.append(f"- {len(seq['records'])} topics with questions in the canonical manifest")
lines.append(f"- {sum(1 for r in seq['records'] if r['CANONICAL_SEQUENCE_HASH'])} canonical-side hashes computed")
lines.append(f"- 0 application-side hashes computed (DB migration not yet run)")
lines.append("")
lines.append("---")
lines.append("")

# 5. Review queue
lines.append("## 5. Unmapped / Synthetic Review Queue")
lines.append("")
lines.append(f"File: `docs/MTG_UNMAPPED_REVIEW_QUEUE.json`")
lines.append("")
lines.append("Per spec §29, every question that cannot be cleanly mapped is kept here —")
lines.append("nothing is silently dropped, randomly assigned, or hidden.")
lines.append("")
lines.append("Queue composition:")
lines.append("")
lines.append("| Source | Items |")
lines.append("|---|---|")
lines.append(f"| `docs/MTG_TOPIC_REPAIR_QUEUE.json` | {rq['queue_breakdown']['topic_repair_queue']['raw_count']} |")
lines.append(f"| `docs/MTG_EXAM_SCORER_REPAIR_QUEUE.json` | {rq['queue_breakdown']['exam_scorer_repair_queue']['raw_count']} |")
lines.append(f"| Application DB synthetic (per audit) | {rq['queue_breakdown']['synthetic_in_app']['count']} |")
lines.append("")
lines.append(f"**Total review items**: {rq['total_review_items']}")
lines.append("")
lines.append("---")
lines.append("")

# 6. Migration procedure
lines.append("## 6. Migration Procedure (DB Integration)")
lines.append("")
lines.append("Per spec §32, this is PHASE 8 (only after PHASE 6 read-only validation passes).")
lines.append("Per spec §13, take a complete DB snapshot before any write operation.")
lines.append("Per spec §14, student progress MUST survive the migration.")
lines.append("")
lines.append("### 6.1 Prerequisites")
lines.append("")
lines.append("```bash")
lines.append("# 1. Ensure .env has a live DATABASE_URL")
lines.append("cp .env.example .env")
lines.append("# Edit .env: set DATABASE_URL to your PostgreSQL/SQLite instance")
lines.append("")
lines.append("# 2. Install dependencies")
lines.append("pnpm install")
lines.append("")
lines.append("# 3. Generate Prisma client")
lines.append("pnpm exec prisma generate")
lines.append("")
lines.append("# 4. Apply schema (creates/migrates tables)")
lines.append("pnpm exec prisma db push    # dev")
lines.append("# OR")
lines.append("pnpm exec prisma migrate deploy  # prod")
lines.append("```")
lines.append("")
lines.append("### 6.2 Pre-migration snapshot (spec §13)")
lines.append("")
lines.append("```bash")
lines.append("# Create a complete DB snapshot before any write")
lines.append("mkdir -p prisma/backups")
lines.append(f"DATE=$(date +%Y%m%d-%H%M%S)")
lines.append(f"cp dev.db prisma/backups/dev.db.pre-mtg-integration.$DATE.bak   # SQLite")
lines.append(f"# OR for PostgreSQL:")
lines.append(f"# pg_dump $DATABASE_URL > prisma/backups/pg.pre-mtg-integration.$DATE.sql")
lines.append("```")
lines.append("")
lines.append("### 6.3 Run the canonical-back-fill migration")
lines.append("")
lines.append("The migration script is `scripts/ingest_mtg_master_pipeline.py` (already in")
lines.append("the repo). It reads the canonical manifest and upserts each question into")
lines.append("the `Question` table using `id` (= canonical source_id) as the deterministic")
lines.append("primary key (per spec §31 IDEMPOTENCY).")
lines.append("")
lines.append("```bash")
lines.append("pnpm exec tsx scripts/ingest_mtg_master_pipeline.py \\")
lines.append("    --manifest docs/MTG_SOURCE_MASTER_MANIFEST.json \\")
lines.append("    --mapping   docs/MTG_NCERT_TOPIC_MAPPING.json \\")
lines.append("    --dry-run   # first run with --dry-run to preview changes")
lines.append("")
lines.append("# Then commit if dry-run is clean:")
lines.append("pnpm exec tsx scripts/ingest_mtg_master_pipeline.py \\")
lines.append("    --manifest docs/MTG_SOURCE_MASTER_MANIFEST.json \\")
lines.append("    --mapping   docs/MTG_NCERT_TOPIC_MAPPING.json")
lines.append("```")
lines.append("")
lines.append("### 6.4 Replacing synthetic questions with authentic source")
lines.append("")
lines.append("For the ~11,284 source questions NOT in the canonical manifest, the migration")
lines.append("requires a re-extraction from the MTG PDFs. Per spec §33, this is normally")
lines.append("forbidden — but the canonical manifest in the repo is incomplete, so the")
lines.append("user must explicitly authorise a re-extraction pass.")
lines.append("")
lines.append("Re-extraction procedure:")
lines.append("")
lines.append("1. Download the 3 MTG PDFs from the Google Drive folder")
lines.append(f"   (ID `{inventory['metadata']['sourceLocation'].split(': ')[-1]}`):")
lines.append("   - `biology_fingertips.pdf` (1029 pages)")
lines.append("   - `chemistry_fingertips.pdf` (853 pages)")
lines.append("   - `physics_fingertips.pdf` (500 pages)")
lines.append("")
lines.append("2. Run the VLM-based extractor (per the canonical-extraction spec from the")
lines.append("   previous session — see `scripts/integration/` for the reference impl):")
lines.append("")
lines.append("   ```bash")
lines.append("   # For each chapter in docs/MTG_AUTHORITATIVE_SOURCE_INVENTORY.json:")
lines.append("   python3 scripts/integration/04_vlm_extract_chapter.py \\")
lines.append("       <book_id> <pdf_page_start> <pdf_page_end> \\")
lines.append("       --class <11|12> --chapter <N> --chapter-title '<title>'")
lines.append("   ```")
lines.append("")
lines.append("3. Each VLM run appends canonical records to")
lines.append("   `data/canonical/<book_id>/ch<N>/questions.jsonl`.")
lines.append("")
lines.append("4. Run the canonical merger to extend `docs/MTG_SOURCE_MASTER_MANIFEST.json`")
lines.append("   with the new verbatim question text, options, and answers.")
lines.append("")
lines.append("5. Re-run the migration script (idempotent — only new records are inserted,")
lines.append("   existing records with the same `id` are updated with verbatim text).")
lines.append("")
lines.append("### 6.5 Post-migration validation")
lines.append("")
lines.append("```bash")
lines.append("# Run the existing auditor")
lines.append("pnpm exec tsx src/lib/auditor/engine.ts --mode validate --report docs/MTG_POST_MIGRATION_AUDIT.json")
lines.append("")
lines.append("# Compute application-side sequence hashes and compare to canonical")
lines.append("python3 scripts/integration/03_validate_app_sequences.py \\")
lines.append("    --mapping docs/MTG_NCERT_TOPIC_MAPPING.json \\")
lines.append("    --output  docs/MTG_SEQUENCE_VALIDATION.json")
lines.append("```")
lines.append("")
lines.append("Per spec §22, a chapter is COMPLETE only when:")
lines.append("- every NCERT topic has the canonical count of questions in the DB")
lines.append("- every question's `Question.fingerprint` matches the canonical SHA-256")
lines.append("- every topic's app-side sequence hash matches the canonical-side hash")
lines.append("- zero records have `verificationStatus = 'NEEDS_REVIEW'`")
lines.append("")
lines.append("---")
lines.append("")

# 7. Frontend integration
lines.append("## 7. Frontend Integration")
lines.append("")
lines.append("The repo already has the frontend wiring for MTG Practice:")
lines.append("")
lines.append("- **API route**: `src/app/api/ncert/mtg/inventory/route.ts`")
lines.append("  Returns the canonical MTG inventory (chapters + topics + question counts).")
lines.append("- **API route**: `src/app/api/ncert/mtg/topic-audit/route.ts`")
lines.append("  Returns per-topic audit data (canonical count vs app count, hash match, etc).")
lines.append("- **Frontend page**: `src/app/ncert/mtg-inventory/page.tsx`")
lines.append("  Renders the MTG inventory dashboard.")
lines.append("")
lines.append("Per spec §16, the student-facing flow is:")
lines.append("")
lines.append("```")
lines.append("NCERT → Subject → Class → Chapter → Topic 1.1 → MTG Practice")
lines.append("                                                       ↓")
lines.append("                                              Q1 → Q2 → Q3 → ...")
lines.append("                                              (in canonical source order)")
lines.append("```")
lines.append("")
lines.append("The existing API routes already fetch questions ordered by")
lines.append("`originalQuestionNumber` within each `Topic`. The frontend renders them in")
lines.append("that order. As long as the migration script populates `Question.originalQuestionNumber`")
lines.append("from the canonical manifest's `id` suffix (e.g. `Q_FT_MTG_KEPH101_T1_1_01` →")
lines.append("`originalQuestionNumber = 1`), the source sequence is preserved.")
lines.append("")
lines.append("Per spec §27 (UI QA), after migration the following must be manually verified:")
lines.append("")
lines.append("- [ ] Open `Class 11 → Physics → Chapter 1 → Topic 1.1 → MTG Practice`")
lines.append("- [ ] Verify the exact canonical MTG 1.1 MCQs appear in source order")
lines.append("- [ ] Repeat for 1.2, 1.3, 1.4, ...")
lines.append("- [ ] Repeat for several chapters across all three subjects")
lines.append("- [ ] Open Exam Scorer section for a chapter and verify subsection questions")
lines.append("")
lines.append("---")
lines.append("")

# 8. Idempotency
lines.append("## 8. Idempotency (spec §31)")
lines.append("")
lines.append("Running the integration multiple times MUST NOT create duplicate questions.")
lines.append("The migration script uses `Question.id` (= canonical source_id) as the")
lines.append("deterministic primary key. Re-running the script:")
lines.append("")
lines.append("1. Existing records with the same `id` → UPDATE (text/options/answer refreshed)")
lines.append("2. New records (from extended canonical manifest) → INSERT")
lines.append("3. Records in the DB not in the canonical manifest → leave untouched")
lines.append("   (so student attempts on legacy questions are preserved)")
lines.append("")
lines.append("Per spec §31, re-running the integration results in:")
lines.append("- same question count (per chapter / per topic)")
lines.append("- same mappings")
lines.append("- same ordering (deterministic source_id ordering)")
lines.append("- same SHA-256 fingerprints (deterministic hash of canonical question text)")
lines.append("")
lines.append("### 8.1 Student progress preservation (spec §14)")
lines.append("")
lines.append("The migration NEVER deletes a `Question` row. It only:")
lines.append("- INSERT new rows for canonical source_ids not yet in DB")
lines.append("- UPDATE existing rows to refresh `questionText` / `correctOption` /")
lines.append("  `explanation` / `fingerprint` from the canonical manifest")
lines.append("")
lines.append("Student data preserved:")
lines.append("- `StudentResponse` (attempts)")
lines.append("- `StudentMistake` (incorrect-question tracking)")
lines.append("- `StudentBookmark` (saved questions)")
lines.append("- `RevisionSchedule` (SM-2 spaced repetition)")
lines.append("- `TopicProgress` (per-topic completion)")
lines.append("")
lines.append("All student data joins to `Question.id` which is the canonical source_id —")
lines.append("stable across migrations.")
lines.append("")
lines.append("---")
lines.append("")

# 9. Validation commands
lines.append("## 9. Validation Commands")
lines.append("")
lines.append("```bash")
lines.append("# Build the deterministic mapping registry (idempotent)")
lines.append("python3 scripts/integration/01_build_mapping_and_queues.py")
lines.append("")
lines.append("# Generate the audit report")
lines.append("python3 scripts/integration/02_generate_audit_report.py")
lines.append("")
lines.append("# Generate this integration doc")
lines.append("python3 scripts/integration/03_generate_integration_doc.py")
lines.append("")
lines.append("# (After DB migration) Validate app-side sequence hashes")
lines.append("python3 scripts/integration/04_validate_app_sequences.py \\")
lines.append("    --mapping docs/MTG_NCERT_TOPIC_MAPPING.json \\")
lines.append("    --output  docs/MTG_SEQUENCE_VALIDATION.json")
lines.append("")
lines.append("# Existing auditor scripts in the repo")
lines.append("python3 src/lib/auditor/test_suite.py           # full audit test suite")
lines.append("python3 src/lib/auditor/mtg_topic_auditor.py   # topic-drill audit")
lines.append("python3 src/lib/auditor/exam_scorer_auditor.py # exam-scorer audit")
lines.append("python3 src/lib/repair/mtg_topic_repairer.py   # repair engine")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")

# 10. Current status
lines.append("## 10. Current Status — Honest Verdict (spec §28)")
lines.append("")
lines.append("| Spec phase | Status |")
lines.append("|---|---|")
lines.append("| PHASE 1 Inspect project | ✅ DONE — repo cloned, Next.js 16 + Prisma 6.4.1 + SQLite dev |")
lines.append("| PHASE 2 Locate canonical MTG dataset | ✅ DONE — manifest + inventory + registry present |")
lines.append("| PHASE 3 Locate NCERT topic registry | ✅ DONE — `canonical_topic_registry.py` (79 ch × 302 topics) |")
lines.append("| PHASE 4 Audit current MTG database | ✅ DONE — `MTG_EXAM_SCORER_AUDIT_RESULT.json` shows 13750 DB rows, 2101 authentic |")
lines.append("| PHASE 5 Deterministic NCERT↔MTG mapping | ✅ DONE — `docs/MTG_NCERT_TOPIC_MAPPING.json` (460 records) |")
lines.append("| PHASE 6 READ-ONLY validation | ✅ DONE — `docs/MTG_NCERT_INTEGRATION_AUDIT.md` produced |")
lines.append("| PHASE 7 Mapping report | ✅ DONE |")
lines.append("| PHASE 8 Database migration | ⏸️ PENDING — requires live `DATABASE_URL` (none in this clone) |")
lines.append("| PHASE 9 Post-migration validation | ⏸️ PENDING — requires PHASE 8 first |")
lines.append("| PHASE 10 Frontend MTG Practice wiring | ✅ EXISTING — `src/app/api/ncert/mtg/` + `src/app/ncert/mtg-inventory/` present |")
lines.append("| PHASE 11 Exam Scorer connection | ⚠️ PARTIAL — registry has the subsections; verbatim content back-fill pending |")
lines.append("| PHASE 12 Frontend QA | ⏸️ PENDING — requires PHASE 8 first |")
lines.append("| PHASE 13 Final global audit | ✅ DONE (canonical-side) — full audit pending DB migration |")
lines.append("")
lines.append("### 10.1 What's blocking COMPLETE status")
lines.append("")
lines.append("Per spec §28 NO FAKE SUCCESS, the integration CANNOT be marked COMPLETE")
lines.append("until:")
lines.append("")
lines.append("1. The ~11,284 source questions not in the canonical manifest are re-extracted")
lines.append("   from the MTG PDFs (requires the user to authorise re-extraction per §33).")
lines.append("")
lines.append("2. The migration script (`scripts/ingest_mtg_master_pipeline.py`) is run")
lines.append("   against a live `DATABASE_URL` to replace the 11,649 synthetic DB rows")
lines.append("   with authentic source content.")
lines.append("")
lines.append("3. The post-migration validator (`src/lib/auditor/engine.ts`) confirms:")
lines.append("   - `MAPPED == CANONICAL` (per topic, per chapter, per subject)")
lines.append("   - `MISSING == 0`")
lines.append("   - `DUPLICATE == 0`")
lines.append("   - `WRONG_TOPIC == 0`")
lines.append("   - `WRONG_CHAPTER == 0`")
lines.append("   - `SEQUENCE_MISMATCH == 0`")
lines.append("   - `HASH_MISMATCH == 0`")
lines.append("")
lines.append("Per spec §28, until all of the above are zero, the verdict remains")
lines.append("`PARTIAL — METADATA-VERIFIED, CONTENT-BACK-FILL-PENDING`.")
lines.append("")
lines.append("---")
lines.append("")

# 11. Deliverables index
lines.append("## 11. Deliverables Index (spec §34)")
lines.append("")
lines.append("| # | Deliverable | File | Status |")
lines.append("|---|---|---|---|")
lines.append("| 1 | NCERT → MTG mapping registry | `docs/MTG_NCERT_TOPIC_MAPPING.json` | ✅ |")
lines.append("| 2 | Topic-level mapping report | `docs/MTG_NCERT_INTEGRATION_AUDIT.md` §26 | ✅ |")
lines.append("| 3 | Chapter-level audit report | `docs/MTG_NCERT_INTEGRATION_AUDIT.md` §25 | ✅ |")
lines.append("| 4 | Global audit report | `docs/MTG_NCERT_INTEGRATION_AUDIT.md` §24 | ✅ |")
lines.append("| 5 | Unmapped/review queue | `docs/MTG_UNMAPPED_REVIEW_QUEUE.json` | ✅ |")
lines.append("| 6 | Database migration/integration | `scripts/ingest_mtg_master_pipeline.py` (existing) | ✅ (script ready; not run) |")
lines.append("| 7 | Frontend MTG Practice integration | `src/app/api/ncert/mtg/` + `src/app/ncert/mtg-inventory/` (existing) | ✅ (existing) |")
lines.append("| 8 | Exam Scorer integration | `docs/MTG_NCERT_TOPIC_MAPPING.json` (records with `EXAM_SCORER_TYPE`) | ✅ (registry-level) |")
lines.append("| 9 | Automated validator | `src/lib/auditor/test_suite.py` + `engine.py` (existing) | ✅ (existing) |")
lines.append("| 10 | Sequence-hash validator | `docs/MTG_SEQUENCE_VALIDATION.json` (canonical-side) | ✅ (canonical-side) |")
lines.append("| 11 | Documentation | `docs/MTG_INTEGRATION.md` (this file) | ✅ |")
lines.append("")
lines.append("---")
lines.append("")
lines.append("**End of integration documentation.**")

path = os.path.join(DOCS, 'MTG_INTEGRATION.md')
with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(f"wrote {path} ({len(lines)} lines)")
